spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: test
    password: test

logging:
  level:
    r2dbc: DEBUG
    reactor:
      util:
        Loggers: DEBUG
  group:
    r2dbc: org.springframework.r2dbc,org.springframework.data.r2dbc